name: Build
on:
  push:
    branches: [deploy, test]

jobs:
  build_and_push:
    if: "contains(github.event.head_commit.message, 'Build')"
    name: Build and push
    runs-on: main-linux
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build api image
        run: |
          cd todolist
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.API_NAME }}:$GITHUB_REF_NAME-$GITHUB_RUN_ID -f Dockerfile .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.API_NAME }}:$GITHUB_REF_NAME-$GITHUB_RUN_ID